{
 "title": "Backend Metrics",
 "tags": [ "victoriametrics" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "datasource",
    "query": "victoriametrics-metrics-datasource"
   },
   { "name": "project", "query": { "query": "label_values(project_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Error Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{project_name=\"${project}\", status=~\"5..\"}[1m])) / sum(rate(http_requests_total{project_name=\"${project}\"}[1m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Распределение HTTP-статусов",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (increase(http_requests_total{project_name=\"${project}\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Per Second (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{project_name=\"${project}\"}[1m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(http_requests_total{project_name=\"${project}\", status=~\"5..\"}[1m])) by (method, path)",
     "legendFormat": "5xx {{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Соотношение RPS и Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(path) (\r\n  rate(http_requests_total{project_name=\"${project}\"}[1m])\r\n)",
     "legendFormat": "{{path}} - RPS"
    },
    {
     "expr": "(\r\n  sum by(path) (rate(http_request_duration_seconds_sum{project_name=\"${project}\"}[1m]))\r\n  /\r\n  sum by(path) (rate(http_request_duration_seconds_count{project_name=\"${project}\"}[1m]))\r\n) * 1000",
     "legendFormat": "{{path}} - Latency"
    }
   ]
  },
  {
   "title": "Топ самых популярных эндпоинтов",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "req/sec" } },
   "targets": [
    {
     "expr": "topk(10, \r\n  sum by(path, method) (\r\n    rate(http_requests_total{project_name=\"${project}\", status=~\"2..\"}[5m])\r\n  )\r\n) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Среднее время ответа (avg latency)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(rate(http_request_duration_seconds_sum{project_name=\"${project}\"}[1m]) / rate(http_request_duration_seconds_count{project_name=\"${project}\"}[1m])) * 1000",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Перцентили (P90, P95, P99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{project_name=\"${project}\"}[1m])) by (le, path))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}