{
 "title": "Database Stats",
 "tags": [
  "postgresql",
  "victoriametrics"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "postgresql", "query": "grafana-postgresql-datasource" },
   {
    "name": "dbname",
    "query": "SELECT datname FROM pg_database WHERE datistemplate = false;"
   },
   {
    "name": "victoriametrics",
    "query": "victoriametrics-metrics-datasource"
   },
   { "name": "project", "query": { "query": "label_values(project_name)" } },
   {
    "name": "sql_max_open_conn",
    "query": {
     "query": "query_result(go_sql_max_open_connections{project_name=\"${project}\", db_name=\"${dbname}\"})"
    }
   }
  ]
 },
 "panels": [
  { "title": "Общая статистика", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Активные подключения",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_sql_in_use_connections{project_name=\"${project}\", db_name=\"${dbname}\"}",
     "legendFormat": "__auto"
    },
    { "expr": "$sql_max_open_conn", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Общее количество подключений",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_sql_open_connections{project_name=\"${project}\", db_name=\"${dbname}\"}",
     "legendFormat": "__auto"
    },
    { "expr": "$sql_max_open_conn", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Максимальное количество подключений",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "$sql_max_open_conn", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Размер БД",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT pg_database_size(current_database()) AS db_size_bytes;"
    }
   ]
  },
  {
   "title": "Размеры таблиц",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    table_name,\r\n    pg_size_pretty(pg_total_relation_size(quote_ident(table_name))) as total_size\r\nFROM information_schema.tables\r\nWHERE table_schema = 'public'\r\nORDER BY pg_total_relation_size(quote_ident(table_name)) DESC\r\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Next audit_log ID",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT last_value AS current_audit_log_id\r\nFROM audit_log_id_seq;"
    }
   ]
  },
  { "title": "Производительность запросов", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Топ-10 самых медленных запросов",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    query AS \"Запрос\",\r\n    ROUND(mean_exec_time::numeric, 2) AS \"Среднее время (мс)\",\r\n    calls AS \"Количество выполнений\",\r\n    ROUND((100 * total_exec_time / SUM(total_exec_time) OVER ())::numeric, 2) AS \"Доля общего времени (%)\"\r\nFROM pg_stat_statements\r\nWHERE query ILIKE '\\-- %'\r\nORDER BY mean_exec_time DESC\r\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Топ-10 самых часто выполняемых запросов",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    query AS \"Запрос\",\r\n    calls AS \"Количество выполнений\",\r\n    ROUND(mean_exec_time::numeric, 2) AS \"Среднее время (мс)\",\r\n    ROUND(total_exec_time::numeric, 2) AS \"Общее время (мс)\"\r\nFROM pg_stat_statements\r\nWHERE query ILIKE '\\-- %'\r\nORDER BY calls DESC\r\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Топ-10 запросов с наибольшим временем выполнения",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    query AS \"Запрос\",\r\n    ROUND(total_exec_time::numeric, 2) AS \"Общее время (мс)\",\r\n    calls AS \"Количество выполнений\",\r\n    ROUND(mean_exec_time::numeric, 2) AS \"Среднее время (мс)\",\r\n    ROUND((100 * total_exec_time / SUM(total_exec_time) OVER ())::numeric, 2) AS \"Доля общего времени (%)\"\r\nFROM pg_stat_statements\r\nWHERE query ILIKE '\\-- %'\r\nORDER BY total_exec_time DESC\r\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Топ-10 запросов с наибольшим количеством возвращаемых строк",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    query AS \"Запрос\",\r\n    rows AS \"Всего строк\",\r\n    calls AS \"Количество выполнений\",\r\n    ROUND(rows/calls::numeric, 2) AS \"Среднее строк на запрос\",\r\n    ROUND(mean_exec_time::numeric, 2) AS \"Среднее время (мс)\"\r\nFROM pg_stat_statements\r\nWHERE query ILIKE '\\-- %'\r\nORDER BY rows DESC\r\nLIMIT 10;"
    }
   ]
  }
 ]
}