{
 "title": "Golang Runtime",
 "tags": [
  "golang",
  "victoriametrics"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "datasource",
    "query": "victoriametrics-metrics-datasource"
   },
   { "name": "project", "query": { "query": "label_values(project_name)" } }
  ]
 },
 "panels": [
  { "title": "Golang runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Golang version",
   "type": "stat",
   "description": "Golang version used.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_info{project_name=\"${project}\"}",
     "legendFormat": "{{instance}}: Golang version"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Golang process uptime.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (instance) (\n  runtime_uptime_milliseconds_total{project_name=\"${project}\"}/1000\n)\nor\navg by (instance) (\n  runtime_uptime{project_name=\"${project}\"}/1000\n)\nor\navg by (instance) (\n  time()-process_start_time_seconds{project_name=\"${project}\"}\n)",
     "legendFormat": "{{instance}}: Uptime"
    }
   ]
  },
  {
   "title": "CGo calls",
   "type": "stat",
   "description": "Number of cgo calls made by the current process",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (instance) (\n  rate(go_cgo_go_to_c_calls_calls_total{project_name=\"${project}\"}[$__rate_interval])\n)\nor\navg by (instance) (\n  rate(process_runtime_go_cgo_calls{project_name=\"${project}\"}[$__rate_interval])\n)",
     "legendFormat": "{{instance}}: CGo calls"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "stat",
   "description": "System threads used.\n",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (instance) (\n  go_threads{project_name=\"${project}\"}\n)",
     "legendFormat": "{{instance}}: Threads used"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "description": "Number of goroutines.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "avg by (instance) (\n  go_goroutines{project_name=\"${project}\"}\n)\nor\navg by (instance) (\n  process_runtime_go_goroutines{project_name=\"${project}\"}\n)",
     "legendFormat": "{{instance}}: Goroutines"
    }
   ]
  },
  {
   "title": "GC duration",
   "type": "timeseries",
   "description": "Amount of time in GC stop-the-world pauses.\nDuring a stop-the-world pause, all goroutines are paused and only the garbage collector can run\n",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "\n  avg by (instance) (\n  go_gc_duration_seconds{project_name=\"${project}\", quantile=\"1\"}\n)\n*10^6",
     "legendFormat": "{{instance}}: GC duration (max)"
    },
    {
     "expr": "\n  avg by (instance) (\n  go_gc_duration_seconds{project_name=\"${project}\", quantile=\"0\"}\n)\n*10^6",
     "legendFormat": "{{instance}}: GC duration (min)"
    },
    {
     "expr": "avg by (instance) (\n  histogram_quantile(0.95, sum(rate(process_runtime_go_gc_pause_ns_bucket{project_name=\"${project}\"}[$__rate_interval])) by (le,instance))\n)",
     "legendFormat": "{{instance}}: GC duration"
    }
   ]
  },
  { "title": "Go runtime: memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Memory",
   "type": "timeseries",
   "description": "Memory reserved from system.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (instance) (\n  go_memstats_sys_bytes{project_name=\"${project}\"}\n)",
     "legendFormat": "{{instance}}: Memory reserved from system"
    },
    {
     "expr": "avg by (instance) (\n  go_memstats_alloc_bytes{project_name=\"${project}\"}\n)",
     "legendFormat": "{{instance}}: Memory allocated from system"
    }
   ]
  },
  {
   "title": "Memory heap",
   "type": "timeseries",
   "description": "Memory used heap.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (instance) (\n  go_memstats_heap_sys_bytes{project_name=\"${project}\"}\n)",
     "legendFormat": "{{instance}}: Memory reserved from system by heap"
    },
    {
     "expr": "avg by (instance) (\n  go_memstats_heap_alloc_bytes{project_name=\"${project}\"}\n)\nor\navg by (instance) (\n  process_runtime_go_mem_heap_alloc_bytes{project_name=\"${project}\"}\n)\nor\navg by (instance) (\n  process_runtime_go_mem_heap_alloc{project_name=\"${project}\"}\n)",
     "legendFormat": "{{instance}}: Heap objects, bytes"
    },
    {
     "expr": "avg by (instance) (\n  go_memstats_heap_idle_bytes{project_name=\"${project}\"}\n)\nor\navg by (instance) (\n  process_runtime_go_mem_heap_idle_bytes{project_name=\"${project}\"}\n)\nor\navg by (instance) (\n  process_runtime_go_mem_heap_idle{project_name=\"${project}\"}\n)",
     "legendFormat": "{{instance}}: Heap idle spans, bytes"
    },
    {
     "expr": "avg by (instance) (\n  go_memstats_heap_inuse_bytes{project_name=\"${project}\"}\n)\nor\navg by (instance) (\n  process_runtime_go_mem_heap_inuse_bytes{project_name=\"${project}\"}\n)\nor\navg by (instance) (\n  process_runtime_go_mem_heap_inuse{project_name=\"${project}\"}\n)",
     "legendFormat": "{{instance}}: Heap in-use spans, bytes"
    },
    {
     "expr": "avg by (instance) (\n  go_memstats_heap_released_bytes{project_name=\"${project}\"}\n)\nor\navg by (instance) (\n  process_runtime_go_mem_heap_released_bytes{project_name=\"${project}\"}\n)\nor\navg by (instance) (\n  process_runtime_go_mem_heap_released{project_name=\"${project}\"}\n)",
     "legendFormat": "{{instance}}: Heap released, bytes"
    }
   ]
  },
  {
   "title": "Memory heap objects",
   "type": "timeseries",
   "description": "Number of allocated heap objects.\nThis changes as GC is performed and new objects are allocated.\n",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
   "targets": [
    {
     "expr": "avg by (instance) (\n  go_memstats_heap_objects{project_name=\"${project}\"}\n)\nor\navg by (instance) (\n  process_runtime_go_mem_heap_objects{project_name=\"${project}\"}\n)",
     "legendFormat": "{{instance}}: Heap allocated objects"
    }
   ]
  },
  {
   "title": "Memory off-heap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (instance) (\n  go_memstats_mspan_sys_bytes{project_name=\"${project}\"}\n)",
     "legendFormat": "{{instance}}: Memory mspan"
    },
    {
     "expr": "avg by (instance) (\n  go_memstats_mcache_sys_bytes{project_name=\"${project}\"}\n)",
     "legendFormat": "{{instance}}: Memory mcache"
    },
    {
     "expr": "avg by (instance) (\n  go_memstats_buck_hash_sys_bytes{project_name=\"${project}\"}\n)",
     "legendFormat": "{{instance}}: Memory buck hash"
    },
    {
     "expr": "avg by (instance) (\n  go_memstats_gc_sys_bytes{project_name=\"${project}\"}\n)",
     "legendFormat": "{{instance}}: Memory gc metadata"
    },
    {
     "expr": "avg by (instance) (\n  go_memstats_other_sys_bytes{project_name=\"${project}\"}\n)",
     "legendFormat": "{{instance}}: Memory other"
    }
   ]
  },
  {
   "title": "Memory stack",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (instance) (\n  go_memstats_stack_sys_bytes{project_name=\"${project}\"}\n)",
     "legendFormat": "{{instance}}: Memory reserved by stack"
    }
   ]
  }
 ]
}