{
 "title": "Logs Metrics",
 "tags": [ "victorialogs" ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "datasource",
    "query": "victoriametrics-logs-datasource"
   },
   { "name": "project", "query": { "query": "" } }
  ]
 },
 "panels": [
  {
   "title": "Total logs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "label.app.project.name:${project}\r\n| stats count() "
    }
   ]
  },
  {
   "title": "Backend logs by level",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label.app.project.name:${project} AND label.app.service.type:backend\r\n| unpack_json\r\n| level:*\r\n| stats by (level) count() total\r\n| sort by(total) desc",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Logs rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "logs/s" } },
   "targets": [
    {
     "expr": "label.app.project.name:${project}\r\n| stats by (label.app.service.name) rate() logs_rate\r\n| filter logs_rate: > 0",
     "legendFormat": "{{label.app.service.name}}"
    }
   ]
  }
 ]
}