{
 "title": "Logs",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "project", "query": { "query": "" } }
  ]
 },
 "panels": [
  {
   "title": "Logs volume",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "label.app.project.name:${project} AND label.app.service.type:in(backend,frontend,all-in-one)\r\n| stats by (_time:1m) count() logs_volume"
    }
   ]
  },
  {
   "title": "Tips and tricks",
   "type": "text",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "options": {
    "content": "#### Unpack and level filter\n```\n| unpack_json\n| level:in(debug,info,warn,error,fatal)\n```"
   }
  },
  {
   "title": "Logs rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "logs/s" } },
   "targets": [
    {
     "expr": "label.app.project.name:${project}\r\n| stats by (label.app.service.name) rate() logs_rate\r\n| filter logs_rate: > 0",
     "legendFormat": "{{label.app.service.name}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "direction": "desc",
     "expr": "label.app.project.name:${project} AND label.app.service.type:in(backend,frontend,all-in-one)"
    }
   ]
  }
 ]
}